kind: pipeline
type: docker
name: integration

steps:
    - name: build
      image: docker/compose
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket into the container
      commands:
        - docker-compose build

    - name: test
      image: docker/compose
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket into the container
      commands:
        - docker-compose run --rm test

    - name: build
      image: mcr.microsoft.com/dotnet/sdk
      commands:
        - dotnet build
 
    - name: test
      image: mcr.microsoft.com/dotnet/sdk
      commands:
        - dotnet test